#!/usr/bin/env python3
import sys
import os
import json


def main():
    if len(sys.argv) < 2:
        print('ERROR: missing command line argument')
        print('usage: genreqs.py <Pipfile.lock>')
        return 1
    lockfile = sys.argv[1]
    if not os.path.isfile(lockfile):
        print('ERROR: file {0} not found'.format(lockfile))
        return 1
    with open(lockfile, 'r') as f:
        content = json.loads(f.read())
    reqs = content.get('default', {})
    # do not include the editable packages (for which current repo contains the source)
    reqs = {k:v for k,v in reqs.items() if v.get('editable') != True}
    output = []
    for name, req in reqs.items():
        version = req.get('version', '')
        extras = req.get('extras', [])
        if extras:
            name += '[{0}]'.format(','.join(extras))
        output.append(name + version)
    output.insert(0, "# autogenerated with make, do no modify by hand")
    with open('requirements.txt', 'w') as f:
        f.write('\n'.join(output))


if __name__ == '__main__':
    sys.exit(main())
