# Makefile ---------------------------------------------------------------------
default_target: help

.PHONY: help
help: ## show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
	| sort \
	| awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'


POETRY = ~/.local/bin/poetry
PACKAGE = [[ package_name ]]

# Environment ------------------------------------------------------------------

.PHONY: setup
setup:
	./scripts/setup.sh
	$(POETRY) install
	$(POETRY) update

.PHONY: clean
clean:
	@find . -name '*.pyc' -delete
	@find . -name '*.pyo' -delete
	@find . -name '*__pycache__*' -delete
	@rm -rf build/
	@rm -rf dist/
	@rm -rf site/
	@rm -rf *.egg-info/
	@rm -rf .coverage*
	@rm -rf .mypy_cache
	@rm -rf [[ package_name ]]/.pytest_cache

# Format -----------------------------------------------------------------------

.PHONY: isort
isort:
	$(POETRY) run isort $(PACKAGE)

.PHONY: black
black:
	$(POETRY) run black $(PACKAGE)

.PHONY: format
format: isort black


# Test -------------------------------------------------------------------------
.PHONY: test
test:
	$(POETRY) run pytest $(PACKAGE)
